# Generated by Django 2.1.5 on 2020-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_id', models.CharField(max_length=128)),
                ('current', models.FloatField(max_length=50)),
                ('voltage', models.FloatField(max_length=50)),
                ('power', models.FloatField(max_length=50)),
                ('total', models.FloatField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='devicelist',
            old_name='deviceRegin',
            new_name='deviceRegion',
        ),
        migrations.RemoveField(
            model_name='devicelist',
            name='current',
        ),
        migrations.RemoveField(
            model_name='devicelist',
            name='power',
        ),
        migrations.RemoveField(
            model_name='devicelist',
            name='total',
        ),
        migrations.RemoveField(
            model_name='devicelist',
            name='voltage',
        ),
    ]
